FROM jenkins/jenkins:lts-jdk17

USER root

# Instala Docker CLI (não o daemon)
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER root
